trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform fmt -check
  displayName: 'Terraform Format'

- script: terraform validate
  displayName: 'Terraform Validate'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'