trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Terraform
  jobs:

  - job: TerraformJob

    steps:

    - checkout: self

    - bash: terraform init
      displayName: Terraform Init

    - bash: terraform fmt -check
      displayName: Terraform Format

    - bash: terraform validate
      displayName: Terraform Validate

    - bash: terraform plan
      displayName: Terraform Plan

    - bash: terraform apply -auto-approve
      displayName: Terraform Apply